# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cycle"
client_id = "a00a2c2c4f1ebae46bc6500b1da31fa3"
application_url = "https://links-isa-cargo-explanation.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://links-isa-cargo-explanation.trycloudflare.com/auth/callback",
  "https://links-isa-cargo-explanation.trycloudflare.com/auth/shopify/callback",
  "https://links-isa-cargo-explanation.trycloudflare.com/api/auth/callback",
  "https://links-isa-cargo-explanation.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-740e12fc.myshopify.com"
